import type { Metadata, Viewport } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing, type Locale } from "@/i18n/routing";
import { Fraunces, Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { JsonLd } from "@/components/JsonLd";
import "../globals.css";

// TODO: replace with actual production domain (e.g. "https://brandname.ca")
const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://example.ca";

// TODO: swap display font if brand calls for a different typeface.
// Fraunces is an editorial variable serif — works well for magazine-style sites.
// Alternative display fonts: Playfair Display, Cormorant Garamond, DM Serif Display.
const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-display",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: Locale }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "meta" });

  return {
    title: t("title"),
    description: t("description"),
    metadataBase: new URL(BASE_URL),
    icons: {
      icon: [
        { url: "/logo/favicon-32.png", sizes: "32x32", type: "image/png" },
        { url: "/logo/favicon-192.png", sizes: "192x192", type: "image/png" },
      ],
      shortcut: "/logo/favicon.ico",
      apple: "/logo/favicon-192.png",
    },
    openGraph: {
      title: t("title"),
      description: t("description"),
      type: "website",
      locale: locale === "ko" ? "ko_KR" : "en_CA",
      // TODO: replace siteName with brand name
      siteName: "{{BRAND_NAME}}",
      url: `${BASE_URL}/${locale}`,
      images: [
        {
          // TODO: replace with actual OG image (generate via scripts/prompts.json)
          url: "/images/editorial/arch-break.jpg",
          width: 1536,
          height: 1024,
          alt: "{{OG_IMAGE_ALT}}",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
      images: ["/images/editorial/arch-break.jpg"],
    },
    alternates: {
      canonical: `${BASE_URL}/${locale}`,
      languages: {
        en: `${BASE_URL}/en`,
        ko: `${BASE_URL}/ko`,
      },
    },
    robots: locale === "ko" ? { index: false, follow: false } : undefined,
  };
}

export const viewport: Viewport = {
  // TODO: update themeColor to match brand accent color
  themeColor: "{{BRAND_ACCENT_HEX}}",
  width: "device-width",
  initialScale: 1,
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// TODO: customize the RealEstateAgent JSON-LD with actual realtor details.
// Replace ALL placeholder values below before launch.
// Static JSON-LD payload — no user input, XSS risk is nil.
const realEstateAgentSchema = JSON.stringify({
  "@context": "https://schema.org",
  "@type": "RealEstateAgent",
  // TODO: replace #realtor-id with a slug (e.g. #jane-doe)
  "@id": `${BASE_URL}/#realtor-id`,
  // TODO: replace with realtor full name
  name: "{{REALTOR_FULL_NAME}}",
  // TODO: replace with brand name
  alternateName: "{{BRAND_NAME}}",
  url: BASE_URL,
  // TODO: replace with actual portrait image path (generated by scripts/prompts.json)
  image: `${BASE_URL}/images/editorial/realtor-portrait-bw.jpg`,
  // TODO: replace with realtor cell phone (E.164 format)
  telephone: "{{REALTOR_PHONE_E164}}",
  priceRange: "$$$",
  // TODO: update knowsLanguage — e.g. ["en"] or ["en", "ko"]
  knowsLanguage: ["en"],
  // TODO: replace with actual cities served
  areaServed: [
    { "@type": "City", name: "{{AREA_1}}" },
    { "@type": "City", name: "{{AREA_2}}" },
    { "@type": "City", name: "{{AREA_3}}" },
  ],
  worksFor: {
    "@type": "RealEstateAgent",
    // TODO: replace with brokerage name
    name: "{{BROKERAGE}}",
    // TODO: replace with brokerage phone (E.164)
    telephone: "{{BROKERAGE_PHONE_E164}}",
    address: {
      "@type": "PostalAddress",
      // TODO: fill in actual brokerage address
      streetAddress: "{{BROKERAGE_STREET_ADDRESS}}",
      addressLocality: "{{BROKERAGE_CITY}}",
      addressRegion: "{{BROKERAGE_PROVINCE_OR_STATE}}",
      postalCode: "{{BROKERAGE_POSTAL_CODE}}",
      addressCountry: "CA",
    },
  },
  // TODO: replace with realtor's Instagram URL (or remove if not applicable)
  sameAs: ["https://www.instagram.com/{{INSTAGRAM_HANDLE}}/"],
  // TODO: replace with 1-2 sentence realtor description
  description: "{{REALTOR_SCHEMA_DESCRIPTION}}",
});

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  return (
    <html
      lang={locale}
      className={`${fraunces.variable} ${inter.variable}`}
      suppressHydrationWarning
    >
      <head>
        {locale === "ko" && (
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
          />
        )}
      </head>
      <body>
        <NextIntlClientProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
        {locale === "en" && <JsonLd schema={realEstateAgentSchema} />}
      </body>
    </html>
  );
}
